### ISSUE TITLE
Fix Windows pathing to use forward slashes

### ISSUE THREAD

**Issue by as3mbus** [reeseschultz/ubump#10] opened 2020-04-14 03:57 UTC
Hey i am trying out ubump for the first time since i find it's quite fascinating reducing project size for each package and make it as single project containing multiple smaller package.

but it seems i am having problem when trying to split the subtree for tagging and separate packages

```
\ Splitting A3 Audio Control Unity with unity as the branch name.(node:5708) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: git subtree split -P D:/Projects/Unity/UPM/A3-UPM/Packages/com.a3.audio-control.unity -b unity
assertion failed:  test Packages/com.a3.audio-control.unity = D:/Projects/Unity/UPM/A3-UPM/Packages/com.a3.audio-control.unity
assertion failed:  test Packages/com.a3.audio-control.unity = D:/Projects/Unity/UPM/A3-UPM/Packages/com.a3.audio-control.unity
assertion failed:  test Packages/com.a3.audio-control.unity = D:/Projects/Unity/UPM/A3-UPM/Packages/com.a3.audio-control.unity
No new revisions were found
    at makeError (C:\Users\Crew\AppData\Roaming\npm\node_modules\ubump\node_modules\execa\lib\error.js:58:11)
    at handlePromise (C:\Users\Crew\AppData\Roaming\npm\node_modules\ubump\node_modules\execa\index.js:114:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:5708) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5708) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
/ Splitting A3 Audio Control Unity with unity as the branch name.Terminate batch job (Y/N)? Y
```
it seems like windows git having problem with handling global path. 

i've tried the command and it does return similar result
but when i'm using relative path (e.g Packages/package-name) it works fine

can it be changed to relative path instead? since we already supposed to call ubump inside a project root

**Comment by reeseschultz** [comment] 2020-04-15 00:44
Hey @as3mbus, thanks for bringing this to my attention—and I appreciate the error output, too.

You caught me in the middle of a move. I'm driving for seven hours tomorrow, and unloading a trailer the next day. I need a few days, and then I'll get back to you.

**Comment by reeseschultz** [comment] 2020-04-15 00:46
Also, just curious, are you using [Git Bash](https://gitforwindows.org/)?

**Comment by as3mbus** [comment] 2020-04-15 01:12
i've tried git bash. the TUI for ubump isn't even working there. 

but powershell seems to work just fine

**Comment by reeseschultz** [comment] 2020-04-23 14:43
Sorry for the wait. I'm looking at this now.

It's odd because, actually, the intention is already that relative paths should be used exclusively with packages—it's just not working for Windows. Usually with this sort of thing, my instinctive consideration is that the difference in path separator syntax, i.e. `/` vs `\` could be the problem. I borrowed a Windows machine so I can test that hunch later today.

**Comment by reeseschultz** [comment] 2020-04-23 18:29
Yup, what a surprise. /s

So `process.cwd()` is used throughout ubump, which outputs with backslashes. Internally, when running the interactive CLI, [glob](https://www.npmjs.com/package/glob) is used to recursively find packages (since unfortunately I cannot assume all users put them directly under `Packages/`). I read glob's docs, and learned that it **only** permits forward slashes, for both input and output.

With that in mind, there are a few things I will now do:

1. Update the README to note that PowerShell is the only confirmed shell to work natively on Windows for ubump (getting others to work is *probably* out of my hands—see [this related (?) issue with Node](https://github.com/nodejs/node/issues/21771))
2. Massage all input to glob calls to only include forward slashes
3. Massage all output of cwd calls to only include forward slashes

That *should* do it, and then I'll close this out. Again, sorry for the wait—and thanks for bringing this to my attention. I'll also do some more testing on Windows to see if there's anything else I need to fix/do.

**Closed** 2020-04-23 20:08 UTC
Labels: good first issue

**Comment by reeseschultz** [comment] 2020-04-23 20:18
@as3mbus, FYI, v0.3.2 has been published with the fix. If you have a local copy, make sure you update it, or alternatively just run `npx ubump`. Please let me know if you have any other questions or concerns.

**Comment by as3mbus** [comment] 2020-04-24 02:22
thank you for the fix. trying it as soon as i have some free time 👍
